name: PikaOS Package Build Only (amd64-v3)

on:
  push:
    branches:
      - main
    paths:
      - '.github/build-nest-v3'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/pikaos-builder:nestv3
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:

    - name: Runner Origin Check
      run: |
        if [ "${{ secrets.RUNNER_ORIGIN }}" = "github" ]; then
          exit 1
        else
          true
        fi
      env:
        RUNNER_ORIGIN: ${{ secrets.RUNNER_ORIGIN }}

    - uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
    
    - name: Update APT Cache
      run: apt-get update -y

    - name: Set Build Config
      run: cp -vf ./pika-build-config/amd64-v3.sh ./pika-build-config.sh

    - name: Build Package
      run: ./main.sh
